{{- range .Values.frontends }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
spec:
  selector:
    app: {{ .name | quote }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
{{- end }}
