{{- range .Values.components }}
{{ $component := . }}
{{- with .inbound }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $component.name }}-inbound"
spec:
  selector:
    app: {{ $component.name | quote }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: 8080
  type: {{ .type | default "ClusterIP" }}
{{- end }}
{{- end }}
{{- end }}
