apiVersion: v1
kind: ServiceAccount
metadata:
  name: mni-cloud
---
apiVersion: v1
kind: Secret
metadata:
  name: mni-cloud.service-account-token
  annotations:
    kubernetes.io/service-account.name: mni-cloud
type: kubernetes.io/service-account-token
