regcred: "regcred"

replicas: 1

components:
  - name: mni-vpc
    image: "ghcr.io/mni-cloud/vpc:main"
    args:
      - --address
      - 0.0.0.0
      - --port
      - 8080
      - --vm-endpoint
      - http://mni-vm
      - --in-cluster
    inbound:
      enabled: true
      port: 8080
      type: LoadBalancer
  - name: mni-vm
    image: "ghcr.io/mni-cloud/vm:main"
    args:
      - --address
      - 0.0.0.0
      - --port
      - 8080
      - --vpc-endpoint
      - http://mni-vpc
      - --in-cluster
    inbound:
      enabled: true
      port: 8081
      type: LoadBalancer
